[book]
authors = ["test"]
language = "zh"
multilingual = false
src = "src"
title = "ai编程通识"


[output.html]
additional-js = ["js/libgif.js", "js/rubbable.js", "js/gif.js"]
additional-css = ["css/gif.css"]